"""empty message

Revision ID: a4526defc049
Revises: 
Create Date: 2021-07-28 15:20:24.305581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4526defc049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('className', sa.String(length=30), nullable=False),
    sa.Column('classDescription', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('img_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img_url')
    op.drop_table('charclasses')
    # ### end Alembic commands ###
