"""empty message

Revision ID: bbbe37367d15
Revises: 
Create Date: 2021-07-28 23:07:43.719778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbe37367d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alignmentName', sa.String(length=40), nullable=False),
    sa.Column('alignmentDescription', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backgroundName', sa.String(length=30), nullable=False),
    sa.Column('backgroundDescription', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('coverImage', sa.String(length=255), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('className', sa.String(length=30), nullable=False),
    sa.Column('classDescription', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raceName', sa.String(length=50), nullable=False),
    sa.Column('raceDescription', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('classId', sa.Integer(), nullable=False),
    sa.Column('raceId', sa.Integer(), nullable=False),
    sa.Column('alignmentId', sa.Integer(), nullable=False),
    sa.Column('backgroundId', sa.Integer(), nullable=False),
    sa.Column('portraitImage', sa.String(length=255), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['alignmentId'], ['alignments.id'], ),
    sa.ForeignKeyConstraint(['backgroundId'], ['backgrounds.id'], ),
    sa.ForeignKeyConstraint(['classId'], ['charclasses.id'], ),
    sa.ForeignKeyConstraint(['raceId'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('races')
    op.drop_table('charclasses')
    op.drop_table('campaigns')
    op.drop_table('backgrounds')
    op.drop_table('alignments')
    # ### end Alembic commands ###
